site_name: SuperSight Docs
pages:
    - Home: index.md
    - Installation: Installation.md
    - Quickstart: Quickstart.md
    - Usage: Usage.md
    - Changelog: Changelog.md
theme: cinder
use_directory_urls: false
